### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by jnarowski** [Kelin2025/vuelidate-forms#1]
I think this project is really interesting, something you'd consider making active again?

**Comment by Kelin2025** [comment]
Hi!

Do you have any suggestions? It works well but I'm not sure what should I add more

**Comment by jnarowski** [comment]
Might be worth talking about, maybe it's enough as is. I like the idea of merging in data and the validation object, since they seem to be duplicates of each other. Wondering how it has served you in your projects and if you have run into any snags with it?

**Comment by Kelin2025** [comment]
I also wrote a mixin with basic form actions (submit/reset/validate), maybe I'll add it to this package on weekends or so

**Comment by jnarowski** [comment]
Would love to chat in realtime sometime. I wrote some other mixins for my form too, maybe we can try and combine it to create something truly reusable. I just want to make sure it's verbose enough to support a variety of situations (vuex etc) and that it's not overly complex. 

Are you on Slack, discourse or any other chats?

**Comment by jnarowski** [comment]
I think one of the biggest challenges I have in my app, is having to switch between 

form.email and $v.form.email.$model depending on if there is validation present or not. It would be great to use only a single value across the entire form, if validation methods are present or not.

**Comment by Kelin2025** [comment]
I need some time to solve my work problems (release soon), I'll return to it later

**Comment by Kelin2025** [comment]
### My suggestion: FormCreator

#### Initialize form creator with global form fields and some options (soon)

```js
import { FormCreator } from 'vuelidate-forms/creator'

// Default form components
import DefaultTextfield from '~/components/forms/Textfield'
import DefaultTextarea from '~/components/forms/Textarea'

export const createForm = new FormCreator({
  types: {
    textfield: DefaultTextfield,
    textarea: DefaultTextarea
  }
}
```

#### Use our `createForm` method to generate form components using vuelidate schema  

e.g. `~/components/post/CreateForm.vue`
```js
import { required } from 'vuelidate'
import { createForm } from './forms'

export default createForm({
  form: {
    // $type for field type
    // $value for initial value
    // All vuelidate validators are passed as functions without $ in name
    // Any additional data can be passed using properties with $ at the start
    title: { $type: 'textfield', $value: 'Initial value', required },
    text: { $type: 'textarea', required, $label: 'Post title' }
  }
})
```

#### Import our component and use anywhere:

```vue
<template>
  <!-- We can use it as v-model with entire form -->
  <!-- Or manually sync only some of fields -->
  <!-- Submit event that triggers form submit (may be async) -->
  <PostCreateForm
    v-model="form"
    @update:title="updateTitle"
    @submit="handleSubmit"
    @reset="formWasReset"
   />
  <!-- You can add custom fields slots for particular reasons -->
  <PostCreateForm v-model="form">
    <!-- For "title" field -->
    <div slot="title" slot-scope="formItem">
      <label>{{formItem.$label}}</label>
      <button @click="() => { formItem.$value = 'test' }">Set "test"</button>
    </div>

    <!-- For fields with type "textfield" -->
    <div slot="textfield" slot-scope="formItem">
      <label>{{formItem.$label}}</label>
      <button @click="() => { formItem.$value = 'test' }">Set "test"</button>
    </div>
  </PostCreateForm>
</template>

<script>
import PostCreateForm from '~/components/post/CreateForm'

export default {
  components: { PostCreateForm },
  data () {
    /* 
      Initial data for form declared in component
      Can override default form $value's
      Or you can just use `PostCreateForm.getInitialForm()
    */
    form: { title: 'Lol', text: 'Smth' }
  },
  methods: {
    /* Submit handler with some methods passed */
    submit (formData, formInstance) {
      formInstance.touch()
      formInstance.$v
      formInstance.pending(true)
      formInstance.pending(false)
      formInstance.reset()
      formInstance.disable()
      formInstance.restore()
      formInstance.setData(newFormData)
      // You can choose only some of fields
      formInstance.field('title').disable()
    }
  }
}
</script>
```

---

Here's how I see this. Waiting for your suggestions :)  
What I've missed:
- Work with `$each`
- Buttons and form controls
- Maybe declare form template for `FormCreator` or `createForm` (declare render function in form creator options with passed `fields` options)
- Declare submit callback right in `createForm` options

**Comment by mesqueeb** [comment]
I'm gonna try this plugin in my production app soon!
Is this still on the "todo"? →　Finish plugin
I thought it was finished?

**Comment by Kelin2025** [comment]
@mesqueeb [this](https://github.com/Kelin2025/vuelidate-forms/issues/1#issuecomment-396053881) is not finished yet but I want it  
Things from README are released

**Comment by hqdo** [comment]
Great plugin! I have made a small change for my use case to ensure all form fields actually have a validator even if you don't specify one. 

I made  minor change in util.js in createValidationsFromSchema line 46 to return instead of null,  { function(val) { return true }} i.e optional field (or field is always valid).

Reason for this is that I am using the $v.form.fieldName for my input models.

**Do you think this is a good idea to add into your plugin?**

**Please see my example usage below:**

```vue
<template>
  <div>
        <form-input label="Container Number" :model="$v.myform.field1" />
        <form-input label="Ocean Bill" :model="$v.myform.field2" />
        <button class="button is-primary" :disabled="$v.$invalid || !$v.$dirty">Save Changes</button>
  </div>
</template>

<script>
import { required, minLength } from "vuelidate/lib/validators";
export default {
  forms: {
    myform: {
      field1: { required, minLength: minLength(10) },
      field2: null // No validator
    }
  }
}
</script>

```
**Then in my form-input component**

```vue
<template>
  <div :class="{ 'v-error': invalid, 'v-dirty': dirty }">
    {{label}}
    <b-input v-else :value="value" @input="input" v-bind="$attrs" v-on="listeners" :has-counter="false" />
  </div>
</template>

<script>
export default {
  inheritAttrs: false,
  props: ["label", "type", "model"],
  data() {
    return {
      value: this.model.$model,
      initialValue: this.model.$model
    };
  },
  methods: {
    input(payload) {
      this.$emit("input", payload);
      this.value = payload;
      this.model.$model = payload; // required to set dirty flags
      this.model.$touch(); // required to set dirty flags
    }
  },
  computed: {
    listeners() {
      const { input, ...listeners } = this.$listeners;
      return listeners;
    },
    invalid() {
      return this.model.$invalid;
    },
    dirty() {
      return !this.model.$invalid && this.model.$model != this.initialValue;
    }
  }
};
</script>
```

**Comment by Kelin2025** [comment]
@hqdo I want to refactor existed code on weekends to get rid of `lodash-es`. So you can send your PR after I do it (if you want to be a part of OSS community 😄)

**Comment by hqdo** [comment]
@Kelin2025 sounds good

**Comment by Kelin2025** [comment]
Finally I refactored this plugin! You're welcome to check this out: #2

**Comment by Kelin2025** [comment]
About `FormCreator` - I'll try to make it on the next weekends  
Now I close this issue
